Programação Para Internet/geoufpi/core/urls.py
from rest_framework.routers import DefaultRouter

from .views import GeneratePdf, GeneratePdfDiaria, GeneratePdfMemo, load_tutor
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

router = DefaultRouter()

urlpatterns = [

    url('^(?P<id>\d+)/pdf/$', GeneratePdf.as_view(), name='gerar-pdf'),
    url('^(?P<id>\d+)/pdf-diaria/$', GeneratePdfDiaria.as_view(), name='diaria'),
    url('^(?P<id>\d+)/memo/$', GeneratePdfMemo.as_view(), name='memo'),
    # url('^(?P<curso_id>\d+)/$', Index.as_view(), name='diaria'),


]

Programação Para Internet/geoufpi/ead/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.utils.translation import gettext_lazy as _
from rest_framework.authtoken.views import obtain_auth_token

from core.urls import router
from core.views import index, detalhes, Registre
from core.views import load_tutor

admin.site.site_header = 'CEAD'
admin.site.site_title = 'CEAD'
# admin.site.index_title = _('Pan/el')

template = "templates/admin/login.html"

urlpatterns = i18n_patterns(
    url(r'^api/token/', obtain_auth_token, name='api-token'),
    url(r'admin/', admin.site.urls, name='admin'),
    url(r'^(?P<id>\d+)$', detalhes, name='index'),
    url(r'^$', index, name='index'),
    url(r'registre/', Registre, name='registrar'),
    url(r'^api/', include(router.urls)),
    url(r'board/', include('core.urls', namespace='board')),
    url(r'^admin/login/$', auth_views.login, {'template_name': template}, name='login'),
    url(r'^cidade/(?P<id>\d+)', load_tutor, name='cidade'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Programação Para Internet/geoufpi/core/models.py
import re

from django.contrib.auth import get_user_model
from django.core import validators
from django.db import models

from .utils import Extenso
from django.utils.translation import ugettext_lazy as _


# Create your models here.
User = get_user_model()


class Polo(models.Model):
    nome = models.CharField(verbose_name=_("Nome do Polo"), max_length=25)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name =_('Polo')
        verbose_name_plural = _('Polos')


class Tutor(models.Model):
    MASCULINO, FEMININO = "M", "F"
    GENEROS = (
        (MASCULINO, _("Masculino")),
        (FEMININO, _("Feminino")),
    )
    TIPO = (
        ('T', 'Tutor'),
        ('CG', _('Coordenador Geral')),
        ('CC', _('Coordenador Curso')),
        ('CT', _('Coordenador de Tutoria')),
        ('CP', _('Coordenador de Polo')),
        ('PF', _('Professor Formador')),
        ('PC', _('Professor Conteudista')),
        ('AD', _('Assistente a Docencia')),
        ('O', _('Outros')),
    )
    FORMACAO = (
        ('D', _('Doutor')),
        ('M', _('Mestre')),
        ('E', _('Especialista')),
        ('O', _('Outros')),
    )
    TIPO_CONTA = (
        ('CC', _('Conta Corrente')),
        ('CP', _('Conta Poupança')),
    )
    UF_CHOICES = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranão'),
        ('MG', 'Minas Gerais'),
        ('MS', 'Mato Grosso do Sul'),
        ('MT', 'Mato Grosso'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PE', 'Pernanbuco'),
        ('PI', 'Piauí'),
        ('PR', 'Paraná'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('RS', 'Rio Grande do Sul'),
        ('SC', 'Santa Catarina'),
        ('SE', 'Sergipe'),
        ('SP', 'São Paulo'),
        ('TO', 'Tocantins')
    )

    user = models.ForeignKey('user.User', verbose_name=_("usuario"),related_name="tutor")
    polo = models.ForeignKey('core.Polo', verbose_name=_("Polo"), related_name="tutor")
    curso = models.ForeignKey('core.Curso', verbose_name=_("Curso"), related_name="cursos", blank=False, null=True)
    nome = models.CharField(verbose_name=_("Nome Completo"), max_length=70, blank=False, null=True)
    pais = models.CharField(verbose_name=_('Pais'),blank=False, null=False, max_length=35)
    cidade = models.CharField(verbose_name=_('Cidade'),blank=False, null=False, max_length=35)
    bairro = models.CharField(verbose_name=_('Bairro'),blank=False, null=False, max_length=35)
    logradouro = models.CharField(blank=True, null=False, max_length=35)
    numero = models.CharField(verbose_name=_('Numero'),blank=False, null=False, max_length=35)
    cep = models.CharField(max_length=9, blank=False, validators=[
        validators.RegexValidator(re.compile(r"^\d{8}$|^\d{5}-\d{3}$"),
                                  message="Informe um cep valido no formato 88888888 ou 88888-888", code="invalid")])
    # estado = models.CharField(blank=False, null=False, max_length=35)
    gender = models.CharField(verbose_name="Genero", max_length=1, choices=GENEROS, blank=False, null=True)
    tipo = models.CharField(verbose_name=_("Tipo"), max_length=2, default="T", choices=TIPO, blank=False, null=True)
    formacao = models.CharField(verbose_name=_("Formacao"), max_length=2, default="O", choices=FORMACAO, blank=False,
                                null=True)
    estado = models.CharField(verbose_name=_("Estado"), max_length=2, choices=UF_CHOICES, blank=False, null=True)
    banco = models.CharField(verbose_name=_("Nome do Banco"), max_length=25)
    agencia = models.CharField(verbose_name=_("Agencia Bancaria"), max_length=12)
    conta = models.CharField(verbose_name=_("Numero da Conta"), max_length=12)
    rg = models.CharField(verbose_name="RG", max_length=15, blank=True, null=True)
    telefone = models.CharField(verbose_name=_("Telefone"), max_length=15, blank=True, null=True)
    expedidor = models.CharField(verbose_name=_("Orgao Expedidor"), max_length=15, blank=True, null=True)
    cpf = models.CharField(verbose_name="CPF", max_length=15)
    image = models.ImageField(
        upload_to='core/static/images', verbose_name=_('Imagem'), null=False, blank=True
    )
    email = models.EmailField('E-mail', blank=True, null=True)
    tipo_conta = models.CharField(verbose_name=_("Tipo de Conta"), max_length=2, choices=TIPO_CONTA, blank=False,
                                  null=True)

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Tutor, self).save()
        user = self.user
        user.image = self.image
        self.nome = user.first_name
        user.save()

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = _('Colaborador(a)')
        verbose_name_plural = _('Colaboradores')


class Viagem(models.Model):
    tutor = models.ForeignKey(Tutor, verbose_name=_("tutor"), related_name="relatorios")
    ida = models.DateField(verbose_name=_("Data de Ida"))
    retorno = models.DateField(verbose_name=_("Data de retorno"))
    origem = models.CharField(verbose_name=_("Cidade de Origem"), max_length=25)
    polo = models.ForeignKey('core.Polo', verbose_name=_("Cidade de Destino"), max_length=25)
    is_solicited = models.BooleanField(default=False)
    is_ajuda = models.BooleanField(default=True, verbose_name=_("Ajuda com o transporte"))
    is_relatorio = models.BooleanField(verbose_name=_('È Relatorio'),default=False)
    diarias = models.CharField(verbose_name=_('Diarias'),max_length=3, blank=False, validators=[
        validators.RegexValidator(re.compile(r"((0)|(1)|(2)|(3)|(4)){1}[.]((0)|(5))"),
                                  message="Informe a diaria no formato X.X exemplo: 1.5", code="invalid")])

    def __str__(self):
        return self.tutor.nome + " " + self.ida.__str__() + " " + self.retorno.__str__()

    @property
    def valor_total_str(self):
        self.valor_total
        reais, centavos = str(self.valor_total).split(".")
        if len(centavos) == 1:
            centavos = centavos + '0'
        return reais + ',' + centavos

    @property
    def ajuda_de_custo_extenso(self):
        ajuda = 95.0
        reais, centavos = str(ajuda).split(".")
        if len(centavos) == 1:
            centavos = centavos + '0'
        return Extenso(reais, centavos)

    @property
    def valor_total(self):
        valor_base = 177.00
        diarias = float(self.diarias)
        if self.is_ajuda == True:
            valor_total = diarias * valor_base
            valor_total = valor_total + 95
        else:
            valor_total = diarias * valor_base
        return valor_total

    @property
    def extenso(self):
        reais, centavos = str(self.valor_total).split(".")
        if len(centavos) == 1:
            centavos = centavos + '0'
        return Extenso(reais, centavos)

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Viagem, self).save()

    class Meta:
        verbose_name = _('Viagem')
        verbose_name_plural = _('Viagens')


class Curso(models.Model):
    nome = models.CharField(verbose_name=_("Nome do Curso"), max_length=45)
    image = models.ImageField(
        upload_to='core/static/images', verbose_name=_('Imagem'), null=False, blank=False
    )

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = _('Curso')
        verbose_name_plural = _('Cursos')


class Relatorio(models.Model):
    TIPO_DE_DIARIA = (
        ("N", _("Nacionais")),
        ("I", _("Internacionais")),
    )
    MEIO_DE_TRANSPORTE = (
        ("M", _("Moto")),
        ("C", _("Carro")),
        ("B", _("Onibus")),
        ("Z", _("Aviao")),
        ("O", _("Outros")),
    )
    TIPO_VEICULO = (
        ("O", _("Oficial")),
        ("L", _("Locado")),
        ("P", _("Proprio")),
        ("T", _("Outros")),
    )
    # viagem = models
    viagem = models.OneToOneField('core.Viagem', verbose_name=_("Viagem"), related_name="relatorio")
    dados_da_viagem = models.TextField(verbose_name=_("Dados da Viagem"))
    resultados = models.TextField(verbose_name=_("Resultados Alcançados"), )
    nome_do_condutor = models.CharField(verbose_name=_("Nome do condutor"), max_length=50, blank=True, null=True)
    placa = models.CharField(verbose_name=_("Placa do Veiculo"), max_length=8, blank=True, null=True)
    bilhete_ida = models.CharField(verbose_name=_("Bilhete de Ida"), max_length=20, blank=True, null=True)
    bilhete_volta = models.CharField(verbose_name="Bilhete de Volta", max_length=20, blank=True, null=True)
    tipo = models.CharField(verbose_name=_("Tipo de Diaria"), max_length=1, choices=TIPO_DE_DIARIA, blank=True, null=True)
    tipo_de_veiculo = models.CharField(verbose_name=_("Tipo de Veiculo"), max_length=1, choices=TIPO_VEICULO, blank=True,
                                       null=True)

    transporte = models.CharField(verbose_name=_("Meio de Transporte"), max_length=1, choices=MEIO_DE_TRANSPORTE,
                                  blank=True, null=True)

    def __str__(self):
        return self.viagem.__str__()

    @property
    def is_nacional(self):
        if self.tipo == "N":
            return True
        return False

    @property
    def is_internacional(self):
        if self.tipo == "I":
            return True
        return False

    @property
    def is_carro(self):
        if self.transporte == "C":
            return True
        return False

    @property
    def is_moto(self):
        if self.transporte == "M":
            return True
        return False

    @property
    def is_onibus(self):
        if self.transporte == "B":
            return True
        return False

    @property
    def is_aviao(self):
        if self.transporte == "Z":

Programação Para Internet/geoufpi/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import Tutor


class ColaboradorForm(forms.ModelForm):
    username = forms.CharField(label=_('Username'))
    password = forms.CharField(label=_('Senha'), widget=forms.PasswordInput)
    # telefone = forms.CharField(label=_('Telefone'))

    class Meta:
        model = Tutor
        fields = ('nome', 'telefone', 'cpf', 'email', 'formacao', 'polo', 'tipo', 'curso', 'gender', 'pais',
                  'rg', 'expedidor', 'cidade', 'estado', 'cep', 'bairro', 'logradouro', 'numero', 'banco', 'agencia',
                  'conta', 'tipo_conta',)


class TutorAdminForm(forms.ModelForm):
    username = forms.CharField(max_length=10, label=_('User'))
    password = forms.CharField(widget=forms.PasswordInput, max_length=10, label=_('Password'), required=False, )

    class Meta:
        model = Tutor
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TutorAdminForm, self).__init__(*args, **kwargs)

        if hasattr(self.instance, 'user'):
            self.fields['username'].initial = self.instance.user.username
            self.fields['username'].widget.attrs['readonly'] = True

        self.fields['password'].label = _('New password')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not self.instance:
            if User.objects.filter(username=username).count() > 0:
                raise ValidationError(_('Username ja existe'))
        return username

Programação Para Internet/geoufpi/templates/core/change_forms.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify material_form material_admin %}

{% block extrahead %}
    <link type='text/css' rel="stylesheet" href="{% static 'css/change_forms.css'%}"/>

    {{ block.super }}
    {{ media.css }}
{% endblock %}




{% block brand-logo %}{{ title }}{% endblock %}

{% block breadcrumbs_items %}
    <a href="{% url 'admin:index' %}">{% trans 'Inicio' %}</a>
    <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
    <a class="active" href="{% url opts|admin_urlname:'changelist' %}">
        {% if add %}{% trans 'Adicionar' %} {{ opts.verbose_name }}{% else %}{% trans 'Alterar' %}{% endif %}</a>
{% endblock %}


{% block content %}
    <div class="left-panel change-form">
        <form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post"
              id="{{ opts.model_name }}_form">
            {% csrf_token %}
            {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1"/>{% endif %}
            {% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}"/>{% endif %}
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col s12">

                            {% block change_form %}

                                <div class="tabela">
                                    {% fieldset_layout adminform inline_admin_formsets as layout %}
                                    {% if adminform.form.instance.image %}
                                        <a href={{ adminform.form.instance.image.url }}><span
                                                style="border: black;"><img class="circle responsive-img"
                                                                            src={{ adminform.form.instance.image.url }}></span></a>

                                    {% else %}
                                        <a href="#"><img class="circle responsive-img" src="{% static 'material/imgs/user.png' %}"></a>

                                    {% endif %}

                                    {% form form=adminform.form layout=layout %}

                                    {% endform %}
                                    {% prepopulated_fields_js %}
                                </div>
                            {% endblock %}
                            {% block after_related_objects %}{% endblock %}

                        </div>



                    </div>
                    {% if errors %}
                        <div class="row">
                            <div class="col s12">
                                <small class="errornote">
                                    {% if errors|length == 1 %}{% trans "Por favor, Corrija o erro Abaixo." %}{% else %}
                                        {% trans "Por favor, Corrija o erro Abaixo." %}{% endif %}
                                    <br/><br/>
                                </small>
                            </div>
                        </div>
                    {% endif %}


                </div>
                <div class="card-action">
                    {% submit_row %}
                </div>
            </div>
        </form>
    </div>
    <div class="right-panel">
        {% if not is_popup and change %}
            <div class="z-depth-1">
                {% block object-tools %}
                    <ul class="object-tools collection with-header">
                        <li class="collection-header"><h5>{% trans "Ferramentas" %}</h5></li>
                        {% block object-tools-items %}
                            <li class="collection-item">
                                {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
                                <a href="{% add_preserved_filters history_url %}" class="historylink"><i
                                        class="left material-icons">history</i> {% trans "Historico" %}</a>
                            </li>
                            {% if has_absolute_url %}
                                <li class="collection-item">
                                    <a href="{{ absolute_url }}" class="viewsitelink"><i class="left material-icons">open_in_new</i> {% trans "Ver no Site" %}
                                    </a>
                                </li>
                            {% endif %}
                        {% endblock %}
                        <li class="collection-item">&nbsp;</li>
                    </ul>
                {% endblock %}
                <div style="clear:both"></div>
            </div>
        {% endif %}
    </div>

    {% if adminform and add %}
        <script type="text/javascript">
            $('form#{{ opts.model_name }}_form :input:visible:enabled:first').attr('autofocus', true);
            $('form#{{ opts.model_name }}_form :input:visible:enabled:first').focus();

        </script>
    {% endif %}
{% endblock %}

Programação Para Internet/geoufpi/templates/core/change_viagem.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify material_form material_admin %}

{% block extrahead %}
    <link type='text/css' rel="stylesheet" href="{% static 'css/change_forms.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script>

        $(document).ready(function () {
            $('#id_tutor').change(function () {
                var id = $(this).val();
                setCidade(id);
            });
        });

        function setCidade(id) {
            $.ajax({
                url: '/cidade/' + id,
                dataType: 'JSON',
                jsonpCallback: 'callback',
                contentType: 'application/x-www-form-urlencoded',
                type: 'GET',
                success: function (data) {
                    $('label[for=id_origem]').attr('class', 'active');
                    document.getElementById("id_origem").value = data.cidade;


                }
            });
        }


    </script>
    {{ block.super }}
    {{ media.css }}
{% endblock %}




{% block brand-logo %}{{ title }}{% endblock %}

{% block breadcrumbs_items %}
    <a href="{% url 'admin:index' %}">{% trans 'Inicio' %}</a>
    <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
    <a class="active" href="{% url opts|admin_urlname:'changelist' %}">
        {% if add %}{% trans 'Adicionar' %} {{ opts.verbose_name }}{% else %}{% trans 'Alterar' %}{% endif %}</a>
{% endblock %}


{% block content %}
    <div class="left-panel change-form">
        <form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post"
              id="{{ opts.model_name }}_form">
            {% csrf_token %}
            {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1"/>{% endif %}
            {% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}"/>{% endif %}
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col s12">

                            {% block change_form %}

                                <div class="tabela">
                                    {% fieldset_layout adminform inline_admin_formsets as layout %}


                                    {% form form=adminform.form layout=layout %}

                                    {% endform %}
                                    {% prepopulated_fields_js %}
                                </div>
                            {% endblock %}
                            {% block after_related_objects %}{% endblock %}

                        </div>


                    </div>
                    {% if errors %}
                        <div class="row">
                            <div class="col s12">
                                <small class="errornote">
                                    {% if errors|length == 1 %}{% trans "Por favor, Corrija o erro Abaixo." %}{% else %}
                                        {% trans "Por favor, Corrija o erro Abaixo." %}{% endif %}
                                    <br/><br/>
                                </small>
                            </div>
                        </div>
                    {% endif %}


                </div>
                <div class="card-action">
                    {% submit_row %}
                </div>
            </div>
        </form>
    </div>
    <div class="right-panel">
        {% if not is_popup and change %}
            <div class="z-depth-1">
                {% block object-tools %}
                    <ul class="object-tools collection with-header">
                        <li class="collection-header"><h5>{% trans "Ferramentas" %}</h5></li>
                        {% block object-tools-items %}
                            <li class="collection-item">
                                {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
                                <a href="{% add_preserved_filters history_url %}" class="historylink"><i
                                        class="left material-icons">history</i> {% trans "Historico" %}</a>
                            </li>
                            {% if has_absolute_url %}
                                <li class="collection-item">
                                    <a href="{{ absolute_url }}" class="viewsitelink"><i class="left material-icons">open_in_new</i> {% trans "Ver no Site" %}
                                    </a>
                                </li>
                            {% endif %}
                        {% endblock %}
                        <li class="collection-item">&nbsp;</li>
                    </ul>
                {% endblock %}
                <div style="clear:both"></div>
            </div>
        {% endif %}
    </div>

    {% if adminform and add %}
        <script type="text/javascript">
            $('form#{{ opts.model_name }}_form :input:visible:enabled:first').attr('autofocus', true);
            $('form#{{ opts.model_name }}_form :input:visible:enabled:first').focus();
            console.log($("#id_tutor option:selected").val());
        </script>
    {% endif %}
{% endblock %}